(()=>{'use strict';
const $=id=>document.getElementById(id), mobileClient=/Android|iPhone|iPad|iPod/i.test(navigator.userAgent)||(navigator.platform==='MacIntel'&&navigator.maxTouchPoints>1)||window.Capacitor?.isNativePlatform?.(), icons={grid:'M3 3h7v7H3zm11 0h7v7h-7zM3 14h7v7H3zm11 0h7v7h-7z',camera:'M3 7h4l2-3h6l2 3h4v13H3zm9 3a4 4 0 1 0 0 8 4 4 0 0 0 0-8',spark:'m12 2 2.8 7.2L22 12l-7.2 2.8L12 22l-2.8-7.2L2 12l7.2-2.8Z',game:'M7 7h10c4 0 5 4 5 9s-4 3-6 0H8c-2 3-6 5-6 0s1-9 5-9ZM6 10v5m-2-2.5h4m8-1h.1m3 2h.1',compass:'M12 2a10 10 0 1 0 0 20 10 10 0 0 0 0-20m4 6-3 5-5 3 3-5Z',convert:'M3 5h15l-3-3m3 3-3 3M21 19H6l3 3m-3-3 3-3M6 10v5m12-5v5',download:'M12 3v12m-5-5 5 5 5-5M3 16v5h18v-5',settings:'M12 8a4 4 0 1 0 0 8 4 4 0 0 0 0-8M12 2v3m0 14v3M2 12h3m14 0h3M5 5l2 2m10 10 2 2M5 19l2-2M17 7l2-2',search:'M10 3a7 7 0 1 0 0 14 7 7 0 0 0 0-14m5 12 6 6',upload:'M12 16V3m-5 5 5-5 5 5M3 15v6h18v-6'};
const moduleIcons={spark:'workspace',game:'games',compass:'travel',convert:'convert',schedule:'schedule',decision:'decision'};
function icon(name){if(name==='grid'||name==='cheers'){const i=document.createElement('img');i.className='icon module-icon home-space-icon';i.src=name==='cheers'||document.documentElement.dataset.theme==='night'?'cheers.svg':'folder.svg';i.alt='';i.setAttribute('aria-hidden','true');return i;}if(moduleIcons[name]){const i=document.createElement('img');i.className='icon module-icon';i.src='icons/modules/'+moduleIcons[name]+'.svg';i.alt='';i.setAttribute('aria-hidden','true');return i;}const s=document.createElementNS('http://www.w3.org/2000/svg','svg');s.setAttribute('viewBox','0 0 24 24');s.setAttribute('aria-hidden','true');s.classList.add('icon');const p=document.createElementNS(s.namespaceURI,'path');p.setAttribute('d',icons[name]||icons.download);s.append(p);return s;}document.querySelectorAll('[data-icon]').forEach(e=>{if(e.closest('#moduleNav')){const name={grid:'home-day',spark:'workspace',schedule:'schedule',convert:'convert',decision:'decision',game:'games',compass:'travel',download:'downloads'}[e.dataset.icon];const i=document.createElement('img');i.className='icon nav-icon'+(e.dataset.icon==='grid'?' home-space-icon':'');i.src='icons/navigation/'+name+'.svg';i.alt='';i.setAttribute('aria-hidden','true');e.append(i);}else e.append(icon(e.dataset.icon));});
if(mobileClient){document.documentElement.classList.add('mobile-client');document.querySelectorAll('[data-page=workspace]').forEach(b=>{if(b.classList.contains('primary')){b.dataset.page='convert';b.firstChild.textContent='打开工具箱 ';}else b.remove();});$('workspacePage').remove();document.querySelectorAll('.module-card .card-art>span').forEach((e,i)=>e.textContent=String(i+1).padStart(2,'0'));}
let page='home',theme=null,toastTimer,serviceURL='',serviceCaps=null;
const spaceFor=key=>['workspace','schedule','convert','decision'].includes(key)?'day':['games','travel'].includes(key)?'night':null;
const socialParams=()=>{const q=new URLSearchParams(location.search),out={};for(const key of ['gc_invite','gc_vote']){const value=q.get(key);if(value&&value.length<=16000)out[key]=value;}return out;};
function sendSocial(frame){sendFrame(frame,'guanchao:social-link',{params:socialParams()});}
function refreshSpace(){if(!theme)return;const night=theme==='night';const art=document.querySelector('.tide-art');document.querySelector('.folder-art').hidden=night;document.querySelector('.cheers-art').hidden=!night;art.classList.remove('cheers-active');if(night)requestAnimationFrame(()=>art.classList.add('cheers-active'));document.querySelectorAll('#moduleNav .home-space-icon').forEach(i=>i.src=night?'icons/navigation/home-night.svg':'icons/navigation/home-day.svg');document.querySelectorAll('#moduleNav [data-page],.module-grid [data-page]').forEach(b=>{const space=spaceFor(b.dataset.page);if(space)b.hidden=space!==theme;});$('homeNavLabel').textContent=night?'夜间空间':'日间空间';$('spaceNavCaption').textContent=night?'黑夜 · 一起去生活':'白天 · 把事情做好';$('spaceEyebrow').textContent=night?'黑夜 · 休闲空间':'白天 · 工作空间';$('spaceHeading').replaceChildren(document.createTextNode(night?'一起开局，':'让想法靠岸，'),document.createElement('br'),document.createTextNode(night?'向远方出发':'把事情做好'));const dot=document.createElement('span');dot.textContent='。';$('spaceHeading').append(dot);$('spaceCopy').textContent=night?'挑一款游戏，约一次旅行，把快乐分享给朋友。':'收集灵感、处理文件，给日常留一点从容。';$('spacePrimary').dataset.page=night?'games':mobileClient?'schedule':'workspace';$('spacePrimary').firstChild.textContent=night?'挑一款游戏 ':mobileClient?'安排今天 ':'打开工作台 ';$('spaceShortcut').textContent=night?'回白天做点事 ☀':'去夜间玩一会 ☾';$('spaceSectionTitle').textContent=night?'今晚，自在一点。':'今天，专注一点。';$('spaceSummary').textContent=night?'游戏与旅行':mobileClient?'日程、转换与决定':'日程、灵感、转换与决定';$('spaceArtLabel').textContent=night?'下一次快乐，准备出发':'灵感正在靠岸';if(page==='home')$('pageLabel').textContent=night?'夜间空间':'日间空间';}
const pages={home:'我的观潮',author:'认识作者',workspace:'想好了么',schedule:'安排了么',decision:'定了么',games:'玩了么',travel:'逛了么',convert:'转好了么',downloads:'下载观潮'};
function toast(t){$('toast').textContent=t;$('toast').hidden=false;clearTimeout(toastTimer);toastTimer=setTimeout(()=>$('toast').hidden=true,4500);}
function resumeFrame(frame,key){Promise.all(frame.parentElement.getAnimations().map(a=>a.finished.catch(()=>{}))).then(()=>{if(page===key&&!$('settingsDialog').open)sendFrame(frame,'guanchao:resume');});}
function sendFrame(frame,type,extra={}){try{frame.contentWindow?.postMessage({type,...extra},location.protocol==='file:'?'*':location.origin);}catch{}}
let pageRevision=0,pausePending=null;
async function pauseWorkspace(){const f=$('workspaceFrame');if(!f||!f.hasAttribute('src'))return true;if(pausePending)return pausePending;pausePending=new Promise(resolve=>{const handler=e=>{if(e.source!==f.contentWindow||(e.origin!==location.origin&&!(location.protocol==='file:'&&e.origin==='null'))||e.data?.type!=='guanchao:workspace-paused')return;clearTimeout(timer);removeEventListener('message',handler);resolve(e.data.saved!==false);};const timer=setTimeout(()=>{removeEventListener('message',handler);resolve(false);},3500);addEventListener('message',handler);sendFrame(f,'guanchao:pause');}).finally(()=>pausePending=null);return pausePending;}
async function animateExit(el){if(!el||matchMedia('(prefers-reduced-motion:reduce)').matches)return;const mobile=innerWidth<=800;const a=el.animate([{opacity:1,transform:'translateZ(0) rotateY(0) scale(1)'},{opacity:0,transform:mobile?'translateY(8px) scale(.98)':'translateX(-32px) translateZ(-140px) rotateY(-7deg) rotateX(3deg) scale(.94)'}],{duration:mobile?100:160,easing:'cubic-bezier(.4,0,.6,1)'});try{await a.finished;}catch{}a.cancel();}
async function showPage(next,fromNative=false,spaceOverride=null){const openAuthor=['author','profile'].includes(next);if(openAuthor){next='downloads';$('downloadAuthor').open=true;openAuthorDetails();}if(mobileClient&&next==='workspace')next='home';if(!pages[next])next='home';if(fromNative&&next===page){if(spaceFor(next))setTheme(spaceFor(next));return;}const revision=++pageRevision;if(next===page&&!spaceOverride){if(spaceFor(next))setTheme(spaceFor(next));window.GuanchaoMotion?.clear();document.querySelectorAll('.page').forEach(p=>p.getAnimations().forEach(a=>a.cancel()));const frame=$(page+'Frame');if(frame)resumeFrame(frame,page);if(window.guanchao&&!fromNative)window.guanchao.request('page',{page});return;}if(page==='workspace'&&!await pauseWorkspace()){toast('笔记保存未完成，请在工作台保存后重试');return;}if(revision!==pageRevision)return;document.querySelectorAll('iframe').forEach(f=>sendFrame(f,'guanchao:pause'));if(window.guanchao&&!fromNative){const r=await window.guanchao.request('page',{page:next});if(!r.ok){toast(r.error||'请先保存当前笔记');return;}}if(revision!==pageRevision)return;const oldPage=$(page+'Page');if(page==='home'&&next==='home'&&spaceOverride){window.GuanchaoMotion?.space(theme,spaceOverride);}else{window.GuanchaoMotion?.begin(page,next,{fromSpace:theme,toSpace:spaceOverride||spaceFor(next)||theme});await animateExit(oldPage);}if(revision!==pageRevision)return;page=next;const nextSpace=spaceOverride||spaceFor(next);if(nextSpace&&nextSpace!==theme){setTheme(nextSpace);if(window.guanchao&&!fromNative)window.guanchao.request('theme',{theme:nextSpace});}document.querySelectorAll('.page').forEach(p=>p.hidden=p.id!==next+'Page');$('pageLabel').textContent=next==='home'?(theme==='night'?'夜间空间':'日间空间'):pages[next];document.querySelectorAll('#moduleNav button').forEach(b=>{b.classList.toggle('active',b.dataset.page===next);b.setAttribute('aria-current',b.dataset.page===next?'page':'false');});const f=$(next+'Frame');if(f){if(!f.hasAttribute('src')){const src=new URL(f.dataset.src,location.href);if(['games','travel'].includes(next)){for(const [key,value]of Object.entries(socialParams()))src.searchParams.set(key,value);}f.src=src.href;f.addEventListener('load',()=>{sendFrame(f,'guanchao:theme',{theme});if(['games','travel'].includes(next))sendSocial(f);if(page===next)resumeFrame(f,next);});}else{if(['games','travel'].includes(next))sendSocial(f);resumeFrame(f,next);}}if(next==='downloads'){renderDownloads();if($('downloadAuthor').open)openAuthorDetails();}if(location.hash!== '#'+next)history.replaceState(null,'','#'+next);window.scrollTo({top:0});}
function setTheme(value,persist=true){value=value==='night'?'night':'day';if(theme===value)return;theme=value;document.documentElement.dataset.theme=theme;refreshSpace();window.Capacitor?.Plugins?.SystemBars?.setStyle?.({style:theme==='night'?'DARK':'LIGHT'}).catch(()=>{});$('themeButton').setAttribute('aria-pressed',String(theme==='night'));$('themeButton').setAttribute('aria-label',theme==='night'?'切换白天，打开工作功能':'切换黑夜，打开游戏和旅行');document.querySelector('.theme-caption').textContent=theme==='night'?'夜间':'日间';document.querySelector('.theme-knob').textContent=theme==='night'?'☾':'☀';document.querySelectorAll('iframe').forEach(f=>sendFrame(f,'guanchao:theme',{theme}));if(persist){try{localStorage.setItem('gc-theme-v1',theme);}catch{}}}
async function connect(url,save=true){url=String(url||'').trim().replace(/\/$/,'');if(!url){serviceURL='';serviceCaps=null;updateService();return;}const u=new URL(url);if(!['http:','https:'].includes(u.protocol)||u.username||u.password||u.pathname!=='/'||u.search||u.hash)throw Error('请填写服务根地址，例如 https://你的服务器');if(location.protocol==='https:'&&u.protocol==='http:'&&!window.Capacitor)throw Error('HTTPS网站需要连接HTTPS服务；Windows客户端支持本机服务');const controller=new AbortController(),timer=setTimeout(()=>controller.abort(),7000);try{const r=await fetch(url+'/api/capabilities',{signal:controller.signal});if(!r.ok)throw Error('服务未响应');const c=await r.json();if(!Array.isArray(c.tools))throw Error('这不是观潮转换服务');serviceURL=url;serviceCaps=c;if(save){try{localStorage.setItem('gc-service-v1',url);}catch{}}updateService();}finally{clearTimeout(timer);}}
function updateService(){$('serviceAddress').value=serviceURL;$('serviceStatus').textContent=serviceURL?'已连接 '+serviceURL+' · 文件交给此服务处理':'使用当前设备本地处理';$('engineBadge').textContent=serviceURL?(window.guanchao?'Windows 内置引擎':'已连接转换服务'):'设备本地处理';dispatchEvent(new Event('guanchao:service'));}
async function renderDownloads(){const host=$('downloadCards');if(host.children.length)return;let metadata={};const urls=(window.guanchao||window.Capacitor?.isNativePlatform?.())?['https://giogight.github.io/downloads.json','downloads.json']:['downloads.json'];for(const url of urls){const controller=new AbortController(),timer=setTimeout(()=>controller.abort(),5000);try{const r=await fetch(url,{signal:controller.signal});if(r.ok){metadata=await r.json();break;}}catch{}finally{clearTimeout(timer);}}for(const [name,key,desc]of [['Windows','windows','内置完整转换服务，保留原观潮的平台登录、笔记与收藏。'],['Android','android','手机日程、游戏、旅行与转好了么；桌面日程小组件与转换进度通知。'],['网页版 / iPhone','web','直接打开，无需安装。支持设备本地的常用转换。']]){const card=document.createElement('article');card.className='download-card';card.append(icon(key==='web'?'compass':'download'));const title=document.createElement('h2');title.textContent=name;const p=document.createElement('p');p.textContent=desc;card.append(title,p);const a=document.createElement(key==='web'?'button':metadata[key]?.url?'a':'span');a.className='primary';a.textContent=key==='web'?'继续使用网页版':metadata[key]?.url?'下载 '+(metadata[key].version||''):'安装包信息暂未获取';if(a.tagName==='A'){a.href=metadata[key].url;a.target='_blank';a.rel='noopener';}if(key==='web')a.onclick=()=>showPage('home');card.append(a);host.append(card);}}
document.addEventListener('click',e=>{const b=e.target.closest('[data-page]');if(b){e.preventDefault();showPage(b.dataset.page);}const w=e.target.closest('[data-window]');if(w&&window.guanchao){if(w.dataset.window==='close'){pauseWorkspace().then(saved=>saved?window.guanchao.request('close'):toast('笔记保存未完成，请先保存'));}else window.guanchao.request(w.dataset.window);}});let pendingSpace=null;async function switchSpace(){const next=(pendingSpace||theme)==='day'?'night':'day';pendingSpace=next;try{await showPage('home',false,next);}finally{if(pendingSpace===next)pendingSpace=null;}}
$('themeButton').onclick=switchSpace;$('spaceShortcut').onclick=switchSpace;$('spaceArtButton').onclick=switchSpace;$('spaceArtButton').onkeydown=e=>{if(e.key==='Enter'||e.key===' '){e.preventDefault();switchSpace();}};$('mobileSettings').onclick=$('settingsButton').onclick=()=>{$('settingsDialog').showModal();document.querySelectorAll('iframe').forEach(f=>sendFrame(f,'guanchao:pause'));};$('settingsDialog').addEventListener('close',()=>{const f=$(page+'Frame');if(f)sendFrame(f,'guanchao:resume');});$('connectService').onclick=async()=>{try{$('serviceStatus').textContent='正在检查服务…';await connect($('serviceAddress').value);toast('转换服务已连接');}catch(e){$('serviceStatus').textContent=e.message||'连接失败，请检查地址和网络';}};$('disconnectService').onclick=()=>{connect('');try{localStorage.removeItem('gc-service-v1');}catch{}};
try{setTheme(localStorage.getItem('gc-theme-v1')|| (matchMedia('(prefers-color-scheme:dark)').matches?'night':'day'),false);}catch{}if(window.guanchao){document.body.classList.add('desktop');$('windowButtons').hidden=false;window.guanchao.listen(d=>{if(d.state?.theme)setTheme(spaceFor(page)||d.state.theme,false);if(d.page)showPage(['home','history','bookmarks','browse'].includes(d.page)?'workspace':d.page,true);if(d.notice)toast(d.notice);});window.guanchao.request('init').then(async r=>{if(r.state)setTheme(spaceFor(page)||r.state.theme,false);if(r.serviceUrl){try{await connect(r.serviceUrl,false);}catch{toast('本机转换引擎暂未启动');}}});}else{try{const saved=localStorage.getItem('gc-service-v1');if(saved)connect(saved,false).catch(()=>{});}catch{}}
addEventListener('message',async event=>{const frame=$('scheduleFrame');if(!frame||event.source!==frame.contentWindow||(event.origin!==location.origin&&!(location.protocol==='file:'&&event.origin==='null'))||event.data?.type!=='guanchao:schedule-updated')return;const native=window.GuanchaoNativeAPI?.available?window.GuanchaoNativeAPI:null;if(!native?.syncSchedule){sendFrame(frame,'guanchao:schedule-widget-status',{status:'web'});return;}try{const result=await native.syncSchedule(event.data.data);sendFrame(frame,'guanchao:schedule-widget-status',{status:result?.synced?'synced':'unavailable'});}catch{sendFrame(frame,'guanchao:schedule-widget-status',{status:'failed'});}});
$('taskIsland').onclick=()=>showPage('convert');addEventListener('hashchange',()=>showPage(location.hash.slice(1)));showPage(location.hash.slice(1)||'home');window.Guanchao={icon,toast,showPage,get serviceURL(){return serviceURL;},get capabilities(){return serviceCaps;},get mobile(){return !!mobileClient;},get native(){return window.GuanchaoNativeAPI?.available?window.GuanchaoNativeAPI:null;},updateTask:async task=>{const running=['waiting','running'].includes(task.status);$('taskIsland').hidden=!running;if(running){$('islandTitle').textContent=task.title;$('islandDetail').textContent=task.message;$('islandProgress').textContent=task.progress==null?'…':Math.round(task.progress*100)+'%';}const n=window.GuanchaoNativeAPI?.available?window.GuanchaoNativeAPI:null;if(n)try{const data={id:task.id,title:task.title,subtitle:task.message,progress:task.progress,status:task.status};if(task.nativeStarted){await n[running?'updateTask':'endTask'](data);}else if(running){await n.startTask(data);task.nativeStarted=true;}}catch{}}};
window.Guanchao.saveBlob=async(blob,name,{chooseLocation=false}={})=>{
 const n=window.GuanchaoNativeAPI?.available?window.GuanchaoNativeAPI:null;
 if(n){
  if(blob.size>20*1024*1024)throw Error('此文件超过手机分享的20MB限制，请在浏览器或电脑上保存');
  const base64=await new Promise((resolve,reject)=>{const reader=new FileReader();reader.onload=()=>resolve(reader.result.split(',')[1]);reader.onerror=reject;reader.readAsDataURL(blob);});
  return await n.saveFile({base64,fileName:name,mime:blob.type||'application/octet-stream'});
 }
 if(chooseLocation&&typeof window.showSaveFilePicker==='function'){
  let handle;try{handle=await window.showSaveFilePicker({suggestedName:name});}catch(error){if(error.name==='AbortError')return {saved:'cancelled'};throw error;}
  const writer=await handle.createWritable();try{await writer.write(blob);await writer.close();}catch(error){try{await writer.abort();}catch{}throw error;}
  return {saved:'file',fileName:handle.name};
 }
 const url=URL.createObjectURL(blob),link=document.createElement('a');link.href=url;link.download=name;link.hidden=true;document.body.append(link);link.click();
 setTimeout(()=>{link.remove();URL.revokeObjectURL(url);},60000);
 return {saved:'download-requested'};
};
function openAuthorDetails(){const frame=$('authorFrame');if(!frame)return;if(!frame.hasAttribute('src')){frame.src=frame.dataset.src;frame.addEventListener('load',()=>{sendFrame(frame,'guanchao:theme',{theme});if(page==='downloads'&&$('downloadAuthor').open)resumeFrame(frame,'downloads');});}else if(page==='downloads'&&$('downloadAuthor').open)resumeFrame(frame,'downloads');}
$('downloadAuthor').addEventListener('toggle',()=>{if($('downloadAuthor').open)openAuthorDetails();else sendFrame($('authorFrame'),'guanchao:pause');});
})();
