(()=>{'use strict';
const $=id=>document.getElementById(id),G=window.Guanchao;
const rows=[
['pdf-word','PDF 转 Word','办公文档','pdf','docx','可编辑文字与段落。扫描件请使用 Windows 的 OCR 引擎，复杂排版转换后需校对。'],
['office-pdf','Word / Excel / PPT 转 PDF','办公文档','doc,docx,xls,xlsx,ppt,pptx,rtf,odt,ods,odp','pdf','使用办公文档引擎保留版式，字体差异可能影响排版。'],
['office-format','Office 旧新版互转','办公文档','doc,docx,xls,xlsx,ppt,pptx,rtf','docx,doc,xlsx,xls,pptx,ppt,rtf','选择与原文件对应的文档类型。跨文档类型转换可能不支持。'],
['pdf-excel','PDF 表格转 Excel','办公文档','pdf','xlsx,csv','提取有文字层的表格。扫描表格、复杂合并单元格需人工校对。'],
['pdf-ppt','PDF 转 PPT','办公文档','pdf','pptx','每页作为一张图片放入幻灯片，保留外观；页面内文字和图形不能单独编辑。'],
['images-pdf','图片转 PDF','PDF 工具','jpg,jpeg,png,webp,bmp,tiff,heic','pdf','按选择顺序合并图片，每张一页。可拖入多张图片。'],
['pdf-images','PDF 转图片','PDF 工具','pdf','png,jpg','逐页导出，可选指定页码。'],
['pdf-merge','合并 PDF','PDF 工具','pdf','pdf','按文件列表顺序合并多个 PDF。'],
['pdf-split','拆分 PDF','PDF 工具','pdf','pdf','每页独立保存，也可只拆出指定页。'],
['pdf-compress','压缩 PDF','PDF 工具','pdf','pdf','整理对象并压缩文档流；原文件已充分压缩时，结果可能不会变小。'],
['pdf-rotate','旋转 PDF','PDF 工具','pdf','pdf','旋转全部页面或指定页码。'],
['pdf-delete','删除 PDF 页面','PDF 工具','pdf','pdf','填写要删除的页码，至少保留一页。'],
['pdf-number','PDF 添加页码','PDF 工具','pdf','pdf','在每页底部居中添加数字页码。'],
['image-format','图片格式互转','图片','jpg,jpeg,png,webp,bmp,tif,tiff,heic,avif,gif','jpg,png,webp,bmp,tiff','网页支持浏览器可解码的图片，输出 JPG / PNG / WebP。多帧图片只处理第一帧。'],
['image-resize','图片缩放与压缩','图片','jpg,jpeg,png,webp,bmp,tif,tiff,heic,avif','jpg,png,webp','等比缩小，保留画面比例。JPG 透明部分填白色，PNG 不支持质量压缩。'],
['video-convert','视频格式转换','视频','mp4,mov,mkv,avi,wmv,flv,webm','mp4,mov,mkv,webm','使用 Windows 内置 FFmpeg；按常用兼容编码重新转换。'],
['video-gif','视频片段转 GIF','视频','mp4,mov,mkv,avi,webm','gif','选择起始秒与时长，生成最长30秒的动图。'],
['video-audio','从视频提取音频','音频','mp4,mov,mkv,avi,wmv,webm','mp3,wav,m4a,flac','提取并转换视频的音轨。无音轨的视频无法生成音频。'],
['audio-convert','音频格式转换','音频','mp3,wav,m4a,aac,flac,ogg,mp4','mp3,wav,m4a,aac,flac,ogg','常用音乐、录音格式互转。'],
['csv-xlsx','CSV 转 Excel','表格与文本','csv','xlsx','生成可编辑工作表，原文本以文本单元格保存。'],
['xlsx-csv','Excel 转 CSV','表格与文本','xlsx','csv','导出各工作表；公式读取已保存的结果，不重新计算公式。'],
['json-csv','JSON 表格转 CSV','表格与文本','json','csv','输入为对象数组，例如 [{"姓名":"小文"}]。'],
['csv-json','CSV 转 JSON','表格与文本','csv','json','首行作为字段名，生成对象数组。'],
['text-word','文本 / Markdown 转 Word','表格与文本','txt,md,csv','docx','每行转为 Word 段落；Markdown 保留原文字，不解析复杂排版。'],
['text-pdf','文本转 PDF','表格与文本','txt,md','pdf','Windows 生成可编辑文字 PDF；网页按页面图片输出，保留中文外观。'],
['text-encoding','文本编码转换','表格与文本','txt,md,csv,json','txt','支持 UTF-8、带 BOM 的 UTF-8、UTF-16。GB18030 输出请用 Windows。'],
['archive-list','查看压缩包','解压','zip,rar,7z,tar,gz,tgz','json','查看压缩包内文件名称与大小。网页支持普通 ZIP。'],
['archive-extract','解压文件','解压','zip,rar,7z,tar,gz,tgz,001','zip','ZIP / RAR / 7Z / TAR / GZ，支持密码与分卷的引擎请使用 Windows。分卷需一起选中。'],
['archive-pack','文件打包 ZIP','解压','*','zip','将选择的文件合并为一个 ZIP，保留原文件。']
];
const tools=rows.map(([id,name,category,input,output,description])=>({id,name,category,inputs:input.split(','),outputs:output.split(','),description}));
const localIDs=new Set(tools.filter(t=>!t.id.startsWith('office-')&&!t.id.startsWith('video-')&&!t.id.startsWith('audio-')&&t.id!=='pdf-excel').map(t=>t.id));
let tool=tools[0],category='全部',files=[],busy=false;const tasks=[];if(window.pdfjsLib)pdfjsLib.GlobalWorkerOptions.workerSrc=new URL('vendor/pdf.worker.min.js',location.href).href;
function node(tag,text,cls){const e=document.createElement(tag);if(text!=null)e.textContent=text;if(cls)e.className=cls;return e;}const bytes=n=>n>=1048576?(n/1048576).toFixed(1)+' MB':Math.ceil(n/1024)+' KB';const stem=f=>f.name.replace(/\.[^.]+$/,'');const yieldUI=()=>new Promise(r=>setTimeout(r,0));const cleanName=s=>String(s).replace(/[<>:"/\\|?*\x00-\x1f]/g,'_').slice(0,160)||'文件';
function localAvailable(t=tool){return localIDs.has(t.id);}function serviceAvailable(t=tool){return G.capabilities?.tools?.some(x=>x.id===t.id&&x.available);}
function renderTools(){const q=$('toolSearch').value.trim().toLowerCase();$('toolList').replaceChildren();for(const t of tools.filter(t=>(category==='全部'||t.category===category)&&(!q||(t.name+' '+t.inputs).toLowerCase().includes(q)))){const b=node('button',t.name,t.id===tool.id?'active':'');b.type='button';b.append(node('small',serviceAvailable(t)?'完整引擎':localAvailable(t)?'设备可用':'需完整引擎'));b.onclick=()=>selectTool(t);$('toolList').append(b);}if(!$('toolList').children.length)$('toolList').append(node('p','没有匹配的工具','hint'));}
for(const c of ['全部',...new Set(tools.map(t=>t.category))]){const b=node('button',c,c===category?'active':'');b.type='button';b.onclick=()=>{category=c;document.querySelectorAll('#categoryTabs button').forEach(x=>x.classList.toggle('active',x===b));renderTools();};$('categoryTabs').append(b);}$('toolSearch').oninput=renderTools;addEventListener('guanchao:service',()=>{renderTools();updateNotice();});
function field(key,label,values,value,type='text'){const wrap=node('label',label);let input;if(values){input=node('select');for(const item of values){const pair=Array.isArray(item)?item:[item,item.toUpperCase()];const o=node('option',pair[1]);o.value=pair[0];input.append(o);}}else{input=node('input');input.type=type;input.placeholder=value||'';if(type==='number')input.min='0';}input.id='option-'+key;input.dataset.option=key;if(value!=null&&values)input.value=value;wrap.append(input);$('conversionOptions').append(wrap);}
function selectTool(t){if(busy){G.toast('当前任务完成或取消后可选择其他工具');return;}tool=t;files=[];$('inputFiles').value='';$('inputFiles').accept=t.inputs[0]==='*'?'':t.inputs.map(x=>'.'+x).join(',');$('toolName').textContent=t.name;$('toolDescription').textContent=t.description;$('toolSymbol').textContent=t.id==='pdf-word'?'W':t.category==='解压'?'Z':t.category==='图片'?'▧':t.category==='音频'?'♫':'↔';$('fileHint').textContent=(t.inputs[0]==='*'?'任意文件':t.inputs.join(' / ').toUpperCase())+' · 设备本地最多100 MB，Windows最多512 MB';$('conversionOptions').replaceChildren();if(t.outputs.length>1)field('format','输出格式',t.outputs,t.outputs[0]);if(t.id.startsWith('pdf-')&&t.id!=='pdf-merge'&&t.id!=='pdf-number'&&t.id!=='pdf-compress')field('pages',t.id==='pdf-delete'?'要删除的页码（必填）':'页码范围（留空为全部）',null,'例如 1-3,5');if(t.id==='pdf-rotate')field('angle','顺时针旋转',[['90','90°'],['180','180°'],['270','270°']],'90');if(t.id.startsWith('image')&&t.id!=='images-pdf'){field('width','最大宽度（留空保留原尺寸）',null,'例如 1920','number');field('quality','JPG / WebP 质量',[[85,'85% · 推荐'],[65,'65% · 更小'],[95,'95% · 更清晰']],85);}if(['pdf-word','pdf-excel','pdf-ppt','pdf-images','pdf-split','pdf-rotate','pdf-delete','pdf-number','pdf-compress','pdf-merge','archive-extract','archive-list'].includes(t.id))field('password','打开密码（如需要）',null,'', 'password');if(t.id==='archive-pack'){field('password','ZIP密码（可选，完整引擎）',null,'','password');field('volumeMB','分卷大小 MB（可选，完整引擎）',null,'例如 50','number');}if(t.id==='archive-extract')field('selected','只解压这些路径（可选，用分号分开）',null,'留空解压全部');if(t.id==='video-gif'){field('start','从第几秒开始',null,'0','number');field('duration','持续秒数（最多30）',null,'5','number');}if(t.category==='表格与文本'){field('encoding','原文件编码',[['utf-8','UTF-8'],['utf-8-sig','UTF-8（BOM）'],['gb18030','GB18030 / GBK'],['utf-16','UTF-16']],'utf-8');if(t.id==='text-encoding')field('outputEncoding','输出编码',[['utf-8','UTF-8'],['utf-8-sig','UTF-8（BOM）'],['utf-16','UTF-16'],['gb18030','GB18030']],'utf-8');}renderFiles();renderTools();updateNotice();}
function updateNotice(){$('conversionNotice').textContent=serviceAvailable()?'已连接完整引擎，自动模式优先使用服务。'+(window.guanchao?' 文件只在本机处理。':' 文件将发送到设置中的服务。'):localAvailable()?'可在当前设备直接处理，文件不会上传。'+(tool.id==='pdf-word'?' 设备版提取可编辑文字；扫描件需 Windows OCR。':''):'此工具需要完整转换引擎，请使用 Windows 客户端，或在设置中连接自己的服务。';}
function addFiles(list){if(busy)return;files=[...files,...Array.from(list)];if(files.length>100){files=files.slice(0,100);G.toast('一次最多选择100个文件');}renderFiles();}function renderFiles(){$('selectedFiles').replaceChildren();files.forEach((f,i)=>{const row=node('div',null,'selected-file');row.append(node('span',(i+1)+'. '+f.name),node('small',bytes(f.size)));const b=node('button','×');b.type='button';b.setAttribute('aria-label','移除 '+f.name);b.onclick=()=>{if(!busy){files.splice(i,1);renderFiles();}};row.append(b);$('selectedFiles').append(row);});}$('inputFiles').onchange=e=>{addFiles(e.target.files);e.target.value='';};for(const name of ['dragenter','dragover'])$('dropzone').addEventListener(name,e=>{e.preventDefault();$('dropzone').classList.add('dragging');});$('dropzone').ondragleave=()=>$('dropzone').classList.remove('dragging');$('dropzone').ondrop=e=>{e.preventDefault();$('dropzone').classList.remove('dragging');addFiles(e.dataTransfer.files);};
function options(){const o={};document.querySelectorAll('[data-option]').forEach(e=>{if(e.value!=='')o[e.dataset.option]=e.value;});if(!o.format)o.format=tool.outputs[0];if(o.selected)o.selected=o.selected.split(/[;；]/).map(s=>s.trim()).filter(Boolean);return o;}
function check(task){if(task.cancelled)throw Error('任务已取消');}
async function step(task,p,message){check(task);task.progress=p;task.message=message;renderTask(task);await yieldUI();}
function saveMessage(result,name){
 const saved=result?.saved;
 if(saved==='cancelled')return '已取消保存，'+name+' 仍在这里，可以重新下载。';
 if(saved==='file')return '已保存 '+(result.fileName||name)+'，请到刚才选择的文件夹查看。';
 if(saved==='downloads')return '已保存 '+name+'，请到设备的下载目录查看。';
 if(saved==='shared')return '已完成 '+name+' 的分享。';
 if(saved==='download-requested')return '已请求下载 '+name+'。请查看浏览器的下载列表；未出现文件时，可选择保存位置，或在 Chrome / Edge / Safari 中打开本页重试。';
 return '已打开文件分享，请选择“存储到文件”或保存位置。';
}
async function saveOutput(task,output,index,status,chooseLocation=false){
 status.textContent=chooseLocation?'请在保存窗口选择文件夹。如果没有弹出窗口，可点击下载，或在 Chrome / Edge / Safari 中打开本页。':'正在准备保存 '+output.name+'…';
 try{
  let result;
  if(output.blob)result=await G.saveBlob(output.blob,output.name,{chooseLocation});
  else if(window.guanchao){const response=await window.guanchao.request('native-export',{jobId:task.serviceId,outputIndex:index});if(!response.ok)throw Error(response.error||'导出失败');result={saved:response.cancelled?'cancelled':'file',fileName:output.name};}
  else if(G.native&&output.size<=200*1024*1024)result=await G.native.downloadFile({url:task.serviceURL+output.url,fileName:output.name,mime:output.mime});
  else{const response=await fetch(task.serviceURL+output.url);if(!response.ok)throw Error('输出文件已过期，请重新转换');result=await G.saveBlob(await response.blob(),output.name);}
  status.textContent=saveMessage(result,output.name);
 }catch(error){status.textContent='保存未完成：'+(error.message||'请重试')+'。转换结果仍在这里。';G.toast(error.message||'保存失败');}
}
function renderTask(task){
 if(!task.element){
  const row=node('article',null,'job-row'),title=node('h3',task.title),message=node('p'),bar=node('progress'),actions=node('div',null,'job-actions'),saveStatus=node('p',null,'job-save-status');
  bar.max=1;row.tabIndex=-1;saveStatus.setAttribute('role','status');saveStatus.setAttribute('aria-live','polite');row.append(title,message,bar,actions,saveStatus);
  Object.assign(task,{element:row,titleEl:title,messageEl:message,bar,actions,saveStatus});
  if(tasks.length===1)$('jobList').replaceChildren();$('jobList').prepend(row);
 }
 task.element.classList.toggle('failed',task.status==='failed');task.element.classList.toggle('completed',task.status==='completed');
 task.titleEl.textContent=(task.status==='completed'?'转换完成 · ':task.status==='failed'?'未能转换 · ':'')+task.title;
 task.messageEl.textContent=task.message+(task.warnings?.length?' · '+task.warnings.join(' '):'');
 task.bar.hidden=!['running','waiting'].includes(task.status);if(task.progress==null)task.bar.removeAttribute('value');else task.bar.value=task.progress;
 if(task.actionsStatus!==task.status){
  task.actionsStatus=task.status;task.actions.replaceChildren();
  if(['waiting','running'].includes(task.status)){
   const cancel=node('button','取消任务');cancel.type='button';cancel.onclick=async()=>{task.cancelled=true;if(task.serviceId)try{await fetch(task.serviceURL+'/api/jobs/'+task.serviceId,{method:'DELETE'});}catch{}task.message='正在取消…';renderTask(task);};task.actions.append(cancel);
  }else if(task.status==='completed'){
   task.saveStatus.textContent='已生成 '+task.outputs.length+' 个文件，请点击下载或选择保存位置。关闭、刷新页面会清除尚未保存的结果。';
   task.outputs.forEach((output,index)=>{
    const file=node('div',null,'result-file'),details=node('div',null,'result-file-details'),actions=node('div',null,'result-file-actions');
    details.append(node('strong',output.name),node('small',bytes(output.size)));file.append(details,actions);task.actions.append(file);
    const label='下载 '+(output.name.toLowerCase().endsWith('.docx')?'Word 文件':output.name);
    if(output.blob&&!window.guanchao&&!G.native){
     output.downloadURL=output.downloadURL||URL.createObjectURL(output.blob);
     const link=node('a',label,'result-download');link.href=output.downloadURL;link.download=output.name;link.onclick=()=>{task.saveStatus.textContent=saveMessage({saved:'download-requested'},output.name);};actions.append(link);
     if(typeof window.showSaveFilePicker==='function'){
      const picker=node('button','选择保存位置');picker.type='button';picker.onclick=()=>saveOutput(task,output,index,task.saveStatus,true);actions.append(picker);
     }
     const shareFile=new File([output.blob],output.name,{type:output.mime||'application/octet-stream'});
     if(navigator.canShare?.({files:[shareFile]})){
      const share=node('button','保存 / 分享');share.type='button';share.onclick=async()=>{try{await navigator.share({files:[shareFile]});task.saveStatus.textContent='已完成分享；如要保留文件，请在分享面板选择保存到文件。';}catch(error){task.saveStatus.textContent=error.name==='AbortError'?'已取消分享，文件仍可下载。':'分享未完成，请点击下载保存。';}};actions.append(share);
     }
    }else{
     const save=node('button',G.native?'保存 / 分享文件':label,'result-download');save.type='button';save.onclick=()=>saveOutput(task,output,index,task.saveStatus);actions.append(save);
    }
   });
  }
 }
 if(['completed','failed','cancelled'].includes(task.status)&&!task.resultPresented){
  task.resultPresented=true;task.element.focus({preventScroll:true});task.element.scrollIntoView({block:'center',behavior:'instant'});
  if(task.status==='completed')G.toast('转换完成，请在结果卡片下载文件');
 }
 G.updateTask(task);
}

function output(name,data,mime){const blob=data instanceof Blob?data:new Blob([data],{type:mime||'application/octet-stream'});return {name:cleanName(name),size:blob.size,mime:blob.type,blob};}
async function serviceConvert(task,list,o){task.serviceURL=G.serviceURL;const form=new FormData();form.append('kind',tool.id);form.append('options',JSON.stringify(o));list.forEach(f=>form.append('files',f,f.name));task.progress=null;task.message='正在传送文件给转换引擎';renderTask(task);const r=await fetch(task.serviceURL+'/api/jobs',{method:'POST',body:form});const data=await r.json();if(!r.ok)throw Error(typeof data.detail==='string'?data.detail:'引擎无法接收文件');task.serviceId=data.id;do{if(task.cancelled){await fetch(task.serviceURL+'/api/jobs/'+data.id,{method:'DELETE'});throw Error('任务已取消');}const response=await fetch(task.serviceURL+'/api/jobs/'+data.id);if(!response.ok)throw Error('任务连接中断，请检查转换服务');const j=await response.json();task.status=j.status;task.progress=j.progress;task.message=j.message;task.warnings=j.warnings;task.outputs=j.outputs||[];renderTask(task);if(j.status==='failed')throw Error(j.message);if(j.status==='cancelled')throw Error('任务已取消');if(j.status==='completed')return;await new Promise(r=>setTimeout(r,700));}while(true);}
function pages(text,count){if(!String(text||'').trim())return Array.from({length:count},(_,i)=>i);const set=new Set();for(const part of String(text).trim().split(/[,，\s]+/)){if(!/^\d+(?:-\d+)?$/.test(part))throw Error('页码格式应为 1-3,5');const[a,b=a]=part.split('-').map(Number);if(a<1||b>count||a>b)throw Error('页码超出范围');for(let n=a;n<=b;n++)set.add(n-1);}return [...set];}
async function pdfFile(f,o){const data=new Uint8Array(await f.arrayBuffer());return pdfjsLib.getDocument({data,password:o.password||'',useSystemFonts:true,cMapUrl:new URL('vendor/cmaps/',location.href).href,cMapPacked:true,standardFontDataUrl:new URL('vendor/standard_fonts/',location.href).href}).promise;}
async function canvasPage(pdf,index){const page=await pdf.getPage(index+1),v=page.getViewport({scale:1.5}),c=document.createElement('canvas');c.width=Math.ceil(v.width);c.height=Math.ceil(v.height);await page.render({canvasContext:c.getContext('2d'),viewport:v}).promise;return c;}
function canvasBlob(c,mime='image/png',quality=.85){return new Promise((r,j)=>c.toBlob(b=>b?r(b):j(Error('此浏览器不支持该图片输出格式')),mime,quality));}
async function wordBlob(paragraphs){const d=new docx.Document({sections:[{children:paragraphs.map(text=>new docx.Paragraph({children:[new docx.TextRun({text,font:'Microsoft YaHei'})]}))}]});return docx.Packer.toBlob(d);}
async function pdfText(task,pdf,selection){const lines=[];for(const [pos,i]of selection.entries()){await step(task,pos/selection.length,'提取第 '+(i+1)+' 页文字');const c=await (await pdf.getPage(i+1)).getTextContent();let row='',y=null;for(const item of c.items){if(!('str'in item))continue;const iy=item.transform[5];if(y!=null&&Math.abs(iy-y)>3&&row){lines.push(row);row='';}row+=item.str+(item.hasEOL?'':' ');y=iy;if(item.hasEOL){lines.push(row.trim());row='';y=null;}}if(row)lines.push(row.trim());if(!c.items.some(x=>x.str?.trim()))throw Error('第 '+(i+1)+' 页是扫描件或没有文字层，请用 Windows OCR 转换');lines.push('');}return lines;}
async function localPDF(task,list,o){const result=[],k=tool.id;const f=list[0];if(['pdf-word','pdf-ppt','pdf-images'].includes(k)){const pdf=await pdfFile(f,o);try{if(pdf.numPages>600)throw Error('超过600页，请先拆分');const selection=pages(o.pages,pdf.numPages);if(k==='pdf-word'){result.push(output(stem(f)+'.docx',await wordBlob(await pdfText(task,pdf,selection))));task.warnings=['设备版按文字段落重建，复杂排版请校对。'];}else{const ppt=k==='pdf-ppt'?new PptxGenJS():null;if(ppt)ppt.layout='LAYOUT_WIDE';for(const[pos,i]of selection.entries()){await step(task,pos/selection.length,'生成第 '+(i+1)+' 页');const c=await canvasPage(pdf,i);if(ppt){const slide=ppt.addSlide(),scale=Math.min(13.333/c.width,7.5/c.height),w=c.width*scale,h=c.height*scale;slide.addImage({data:c.toDataURL('image/png'),x:(13.333-w)/2,y:(7.5-h)/2,w,h});}else{const fmt=o.format==='jpg'?'jpg':'png';result.push(output(stem(f)+'-'+(i+1)+'.'+fmt,await canvasBlob(c,fmt==='jpg'?'image/jpeg':'image/png')));}}if(ppt){result.push(output(stem(f)+'.pptx',await ppt.write({outputType:'blob'})));task.warnings=['每页是图片，页面内文字与图形不能单独编辑。'];}}}finally{await pdf.destroy();}return result;}
if(o.password)throw Error('设备版此项不处理加密 PDF，请使用 Windows 完整引擎');const {PDFDocument,degrees,StandardFonts,rgb}=PDFLib;const doc=await PDFDocument.load(await f.arrayBuffer());const selection=pages(o.pages,doc.getPageCount());if(k==='pdf-merge'){const merged=await PDFDocument.create();for(const[pos,file]of list.entries()){await step(task,pos/list.length,'合并 '+file.name);const part=await PDFDocument.load(await file.arrayBuffer());(await merged.copyPages(part,part.getPageIndices())).forEach(p=>merged.addPage(p));}return [output('合并结果.pdf',await merged.save(),'application/pdf')];}if(k==='pdf-split'){for(const[pos,i]of selection.entries()){await step(task,pos/selection.length,'拆分第 '+(i+1)+' 页');const part=await PDFDocument.create();part.addPage((await part.copyPages(doc,[i]))[0]);result.push(output(stem(f)+'-'+(i+1)+'.pdf',await part.save(),'application/pdf'));}return result;}if(k==='pdf-delete'){if(!o.pages)throw Error('请填写要删除的页码');if(selection.length>=doc.getPageCount())throw Error('至少保留一页');selection.sort((a,b)=>b-a).forEach(i=>doc.removePage(i));}if(k==='pdf-rotate')selection.forEach(i=>{const p=doc.getPage(i);p.setRotation(degrees((p.getRotation().angle+Number(o.angle||90))%360));});if(k==='pdf-number'){const font=await doc.embedFont(StandardFonts.Helvetica);doc.getPages().forEach((p,i)=>p.drawText(String(i+1),{x:p.getWidth()/2-5,y:20,size:10,font,color:rgb(.35,.35,.35)}));}await step(task,.85,'保存 PDF 文档');return [output(stem(f)+'-处理后.pdf',await doc.save({useObjectStreams:true}),'application/pdf')];}
async function imageCanvas(f,width){const url=URL.createObjectURL(f);try{const img=new Image();img.src=url;await img.decode();if(img.naturalWidth*img.naturalHeight>80000000)throw Error('图片超过8000万像素，请先缩小');const scale=width?Math.min(1,Number(width)/img.naturalWidth):1,c=document.createElement('canvas');c.width=Math.max(1,Math.round(img.naturalWidth*scale));c.height=Math.max(1,Math.round(img.naturalHeight*scale));c.getContext('2d').drawImage(img,0,0,c.width,c.height);return c;}catch(e){throw Error(e.message==='图片超过8000万像素，请先缩小'?e.message:'浏览器不能解码 '+f.name+'，请使用 Windows 转换');}finally{URL.revokeObjectURL(url);}}
async function localImages(task,list,o){const result=[],pdf=tool.id==='images-pdf'?await PDFLib.PDFDocument.create():null;for(const[pos,f]of list.entries()){await step(task,pos/list.length,'处理 '+f.name);const c=await imageCanvas(f,o.width);if(pdf){const img=await pdf.embedPng(await (await canvasBlob(c)).arrayBuffer());const p=pdf.addPage([c.width*.75,c.height*.75]);p.drawImage(img,{x:0,y:0,width:p.getWidth(),height:p.getHeight()});}else{const fmt=o.format||'jpg';if(!['jpg','png','webp'].includes(fmt))throw Error('设备版输出支持 JPG / PNG / WebP；BMP、TIFF 请使用 Windows');if(fmt==='jpg'){const ctx=c.getContext('2d');ctx.globalCompositeOperation='destination-over';ctx.fillStyle='white';ctx.fillRect(0,0,c.width,c.height);}const blob=await canvasBlob(c,fmt==='jpg'?'image/jpeg':'image/'+fmt,Number(o.quality||85)/100);if(blob.type!==(fmt==='jpg'?'image/jpeg':'image/'+fmt))throw Error('此浏览器不支持 '+fmt+' 输出');result.push(output(stem(f)+'.'+fmt,blob));}}if(pdf)result.push(output('图片合并.pdf',await pdf.save(),'application/pdf'));return result;}
function safeArchivePath(s){if(/^(?:[/\\]|[A-Za-z]:)/.test(s)||s.replaceAll('\\','/').split('/').some(x=>x==='..')||s.includes('\0'))throw Error('压缩包包含越界路径，已停止解压');return s;}
async function localArchive(task,list,o){const k=tool.id;if(k==='archive-pack'){if(o.password||o.volumeMB)throw Error('密码与分卷打包请使用 Windows 完整引擎');const z=new JSZip(),used=new Set();for(const f of list){let name=cleanName(f.name),n=2;while(used.has(name))name=n+++'-'+cleanName(f.name);used.add(name);z.file(name,await f.arrayBuffer());}const blob=await z.generateAsync({type:'blob',compression:'DEFLATE'},p=>{check(task);task.progress=p.percent/100;task.message='打包文件';renderTask(task);});return [output('文件打包.zip',blob)];}if(list.length>1||!list[0].name.toLowerCase().endsWith('.zip')||o.password)throw Error('设备版支持普通单卷 ZIP；密码、RAR / 7Z / TAR 与分卷请使用 Windows');const z=await JSZip.loadAsync(await list[0].arrayBuffer()),entries=Object.values(z.files);if(entries.length>5000)throw Error('设备解压最多5000个条目');let size=0;for(const e of entries){safeArchivePath(e.unsafeOriginalName||e.name);if((Number(e.unixPermissions)&0o170000)===0o120000)throw Error('压缩包包含链接，无法安全解压');size+=Number(e._data?.uncompressedSize||0);}if(size>200*1024*1024)throw Error('设备解压内容最多200 MB，请使用 Windows');if(k==='archive-list')return [output('压缩包文件清单.json',JSON.stringify(entries.map(e=>({name:e.name,size:e._data?.uncompressedSize||0,directory:e.dir})),null,2),'application/json')];const chosen=entries.filter(e=>!e.dir&&(!o.selected||o.selected.includes(e.name)));if(o.selected?.some(s=>!entries.some(e=>e.name===s)))throw Error('填写的文件路径不在压缩包中');if(!chosen.length)throw Error('压缩包中没有可解压的文件');const result=[];for(const[pos,e]of chosen.entries()){await step(task,pos/chosen.length,'解压 '+e.name);result.push(output(e.name,await e.async('blob')));}return result;}
function parseCSV(text){text=text.replace(/^\uFEFF/,'');const rows=[];let row=[],s='',quoted=false;for(let i=0;i<text.length;i++){const c=text[i];if(c==='"'){if(quoted&&text[i+1]==='"'){s+='"';i++;}else if(quoted)quoted=false;else if(!s)quoted=true;else s+=c;}else if(c===','&&!quoted){row.push(s);s='';}else if((c==='\r'||c==='\n')&&!quoted){if(c==='\r'&&text[i+1]==='\n')i++;row.push(s);rows.push(row);row=[];s='';}else s+=c;}if(quoted)throw Error('CSV 引号没有闭合');if(s||row.length){row.push(s);rows.push(row);}return rows;}const csvText=rows=>'\uFEFF'+rows.map(row=>row.map(v=>{let s=String(v??'');if(/^[=+@-]/.test(s))s="'"+s;return /[",\n\r]/.test(s)?'"'+s.replaceAll('"','""')+'"':s;}).join(',')).join('\r\n');const xml=s=>String(s).replaceAll('&','&amp;').replaceAll('<','&lt;').replaceAll('>','&gt;').replaceAll('"','&quot;').replace(/[\x00-\x08\x0b\x0c\x0e-\x1f]/g,'');function colName(i){let s='';for(i++;i;i=Math.floor((i-1)/26))s=String.fromCharCode(65+(i-1)%26)+s;return s;}
async function makeXLSX(rows){const z=new JSZip(),head='<?xml version="1.0" encoding="UTF-8" standalone="yes"?>';z.file('[Content_Types].xml',head+'<Types xmlns="http://schemas.openxmlformats.org/package/2006/content-types"><Default Extension="rels" ContentType="application/vnd.openxmlformats-package.relationships+xml"/><Default Extension="xml" ContentType="application/xml"/><Override PartName="/xl/workbook.xml" ContentType="application/vnd.openxmlformats-officedocument.spreadsheetml.sheet.main+xml"/><Override PartName="/xl/worksheets/sheet1.xml" ContentType="application/vnd.openxmlformats-officedocument.spreadsheetml.worksheet+xml"/></Types>');z.file('_rels/.rels',head+'<Relationships xmlns="http://schemas.openxmlformats.org/package/2006/relationships"><Relationship Id="rId1" Type="http://schemas.openxmlformats.org/officeDocument/2006/relationships/officeDocument" Target="xl/workbook.xml"/></Relationships>');z.file('xl/workbook.xml',head+'<workbook xmlns="http://schemas.openxmlformats.org/spreadsheetml/2006/main" xmlns:r="http://schemas.openxmlformats.org/officeDocument/2006/relationships"><sheets><sheet name="表格" sheetId="1" r:id="rId1"/></sheets></workbook>');z.file('xl/_rels/workbook.xml.rels',head+'<Relationships xmlns="http://schemas.openxmlformats.org/package/2006/relationships"><Relationship Id="rId1" Type="http://schemas.openxmlformats.org/officeDocument/2006/relationships/worksheet" Target="worksheets/sheet1.xml"/></Relationships>');z.file('xl/worksheets/sheet1.xml',head+'<worksheet xmlns="http://schemas.openxmlformats.org/spreadsheetml/2006/main"><sheetData>'+rows.map((r,i)=>'<row r="'+(i+1)+'">'+r.map((v,j)=>'<c r="'+colName(j)+(i+1)+'" t="inlineStr"><is><t xml:space="preserve">'+xml(v)+'</t></is></c>').join('')+'</row>').join('')+'</sheetData></worksheet>');return z.generateAsync({type:'blob',mimeType:'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet',compression:'DEFLATE'});}
async function readXLSX(f){const z=await JSZip.loadAsync(await f.arrayBuffer()),parse=s=>{const d=new DOMParser().parseFromString(s,'application/xml');if(d.querySelector('parsererror'))throw Error('工作表XML无法读取');return d;},shared=z.file('xl/sharedStrings.xml')?Array.from(parse(await z.file('xl/sharedStrings.xml').async('string')).getElementsByTagName('si')).map(e=>e.textContent):[],result=[];const sheets=Object.keys(z.files).filter(s=>/^xl\/worksheets\/sheet\d+\.xml$/.test(s));if(!sheets.length)throw Error('未找到工作表');for(const [i,path]of sheets.entries()){const d=parse(await z.file(path).async('string')),rows=[];for(const row of d.getElementsByTagName('row')){const n=Number(row.getAttribute('r'))-1;if(n>100000)throw Error('工作表超过设备处理上限10万行');const values=[];for(const c of row.getElementsByTagName('c')){const letters=(c.getAttribute('r')||'A1').match(/^[A-Z]+/)[0];let index=0;for(const ch of letters)index=index*26+ch.charCodeAt(0)-64;if(index>16384)throw Error('列数过大');const v=c.getElementsByTagName('v')[0]?.textContent||'';values[index-1]=c.getAttribute('t')==='s'?(shared[Number(v)]||''):c.getAttribute('t')==='inlineStr'?(c.getElementsByTagName('is')[0]?.textContent||''):v;}rows[n]=values;}result.push(output(stem(f)+'-工作表'+(i+1)+'.csv',csvText(Array.from({length:rows.length},(_,j)=>rows[j]||[])),'text/csv;charset=utf-8'));}return result;}
async function textPDF(text){const pdf=await PDFLib.PDFDocument.create(),lines=[],ctx=document.createElement('canvas').getContext('2d');ctx.font='22px sans-serif';for(const line of text.split(/\r?\n/)){let s='';for(const c of line){if(ctx.measureText(s+c).width>940){lines.push(s);s='';}s+=c;}lines.push(s);}for(let n=0;n<Math.max(1,lines.length);n+=36){const c=document.createElement('canvas');c.width=1190;c.height=1684;const cx=c.getContext('2d');cx.fillStyle='white';cx.fillRect(0,0,c.width,c.height);cx.fillStyle='#222';cx.font='22px sans-serif';lines.slice(n,n+36).forEach((s,i)=>cx.fillText(s,100,100+i*38));const img=await pdf.embedPng(await(await canvasBlob(c)).arrayBuffer());pdf.addPage([595,842]).drawImage(img,{x:0,y:0,width:595,height:842});}return pdf.save();}
async function localData(task,list,o){const result=[];for(const[pos,f]of list.entries()){await step(task,pos/list.length,'处理 '+f.name);if(tool.id==='xlsx-csv'){result.push(...await readXLSX(f));continue;}let text;try{text=new TextDecoder(o.encoding==='utf-8-sig'?'utf-8':o.encoding||'utf-8',{fatal:true}).decode(await f.arrayBuffer());}catch{throw Error('无法按所选编码读取文件，请更换原文件编码');}const k=tool.id;if(k==='text-word')result.push(output(stem(f)+'.docx',await wordBlob(text.split(/\r?\n/))));if(k==='text-pdf'){result.push(output(stem(f)+'.pdf',await textPDF(text),'application/pdf'));task.warnings=['设备版按页面图片输出，PDF内文字不可选择。'];}if(k==='csv-xlsx')result.push(output(stem(f)+'.xlsx',await makeXLSX(parseCSV(text))));if(k==='csv-json'){const rows=parseCSV(text),fields=rows.shift()||[];if(new Set(fields).size!==fields.length)throw Error('CSV 首行含重复字段名，请先修改');result.push(output(stem(f)+'.json',JSON.stringify(rows.map(r=>Object.fromEntries(fields.map((h,i)=>[h,r[i]??'']))),null,2),'application/json'));}if(k==='json-csv'){const rows=JSON.parse(text);if(!Array.isArray(rows)||!rows.every(r=>r&&typeof r==='object'&&!Array.isArray(r)))throw Error('JSON 需要是对象数组');const fields=[...new Set(rows.flatMap(r=>Object.keys(r)))];result.push(output(stem(f)+'.csv',csvText([fields,...rows.map(r=>fields.map(h=>typeof r[h]==='object'?JSON.stringify(r[h]):r[h]??''))]),'text/csv;charset=utf-8'));}if(k==='text-encoding'){const enc=o.outputEncoding||'utf-8';if(enc==='gb18030')throw Error('GB18030 输出请使用 Windows 引擎');let data;if(enc==='utf-16'){const buf=new Uint8Array(2+text.length*2),view=new DataView(buf.buffer);view.setUint16(0,0xfeff,true);for(let i=0;i<text.length;i++)view.setUint16(2+i*2,text.charCodeAt(i),true);data=buf;}else data=new TextEncoder().encode((enc==='utf-8-sig'?'\uFEFF':'')+text);result.push(output(stem(f)+'-转换后'+f.name.slice(stem(f).length),data,'text/plain')); }}return result;}
$('convertForm').onsubmit=async e=>{e.preventDefault();if(busy)return;if(!files.length){G.toast('请先选择文件');return;}const list=[...files],o=options(),mode=$('processEngine').value,useService=mode==='service'||mode==='auto'&&serviceAvailable();if(useService&&!serviceAvailable()){G.toast('此工具的完整引擎尚未连接，请检查设置');return;}if(!useService&&!localAvailable()){G.toast('此工具需要 Windows 或连接的转换服务');return;}if(list.reduce((s,f)=>s+f.size,0)>(useService?512:100)*1024*1024){G.toast('文件超过本次处理体积上限');return;}if(['pdf-word','pdf-excel','pdf-ppt','pdf-images','pdf-split','pdf-compress','pdf-rotate','pdf-delete','pdf-number','archive-list'].includes(tool.id)&&list.length!==1){G.toast('此工具一次请选择一个文件');return;}if(tool.id==='pdf-merge'&&list.length<2){G.toast('合并 PDF 至少选择两个文件');return;}if(tool.id==='pdf-delete'&&!o.pages){G.toast('请填写要删除的页码');return;}const task={id:crypto.randomUUID?.()||'task-'+Date.now(),title:tool.name,status:'running',progress:0,message:'准备文件',outputs:[],warnings:[]};tasks.push(task);busy=true;$('startConversion').disabled=true;renderTask(task);try{if(useService)await serviceConvert(task,list,o);else{const k=tool.id;task.outputs=k.startsWith('pdf-')?await localPDF(task,list,o):k.startsWith('image')?await localImages(task,list,o):k.startsWith('archive-')?await localArchive(task,list,o):await localData(task,list,o);check(task);if(!task.outputs.length)throw Error('没有生成输出文件');task.status='completed';task.progress=1;task.message='处理完成，源文件保留';}}catch(e){task.status=task.cancelled||e.message==='任务已取消'?'cancelled':'failed';task.message=task.status==='cancelled'?'任务已取消，源文件保留':e.message||'文件无法处理，请检查文件格式';}finally{busy=false;$('startConversion').disabled=false;renderTask(task);}};selectTool(tool);
})();
