(function(root,factory){const value=factory();if(typeof module==='object'&&module.exports)module.exports=value;else root.GuanchaoPlaceCatalog=value.create();})(typeof window!=='undefined'?window:this,()=>{'use strict';
const cityName=value=>String(value||'').trim().replace(/市$/,'');
const folded=value=>String(value||'').toLowerCase().replace(/[\s·•、()（）\-—]/g,'');
const point=p=>p&&typeof p.lat==='number'&&typeof p.lon==='number'&&Number.isFinite(p.lat)&&Math.abs(p.lat)<=90&&Number.isFinite(p.lon)&&Math.abs(p.lon)<=180;
function distance(a,b){const rad=Math.PI/180,x=Math.sin((b.lat-a.lat)*rad/2)**2+Math.cos(a.lat*rad)*Math.cos(b.lat*rad)*Math.sin((b.lon-a.lon)*rad/2)**2;return 6371000*2*Math.atan2(Math.sqrt(x),Math.sqrt(Math.max(0,1-x)));}
function normalize(raw){if(!raw||!/^tripcom:[1-9]\d{0,15}$/.test(raw.id)||typeof raw.name!=='string'||!raw.name.trim()||raw.name.length>120||typeof raw.city!=='string'||!raw.city.trim()||raw.city.length>80||!['food','drink','play'].includes(raw.category)||!/^\d{4}-\d{2}-\d{2}$/.test(raw.checkedAt||''))return null;let url;try{url=new URL(raw.url);if(url.protocol!=='https:'||url.username||url.password||!['www.trip.com','trip.com'].includes(url.hostname))return null;}catch{return null;}const hasPoint=point(raw),rating=Number(raw.rating),count=Number(raw.reviewCount);return {id:raw.id,name:raw.name.trim(),city:cityName(raw.city),category:raw.category,lat:hasPoint?raw.lat:null,lon:hasPoint?raw.lon:null,address:String(raw.address||'').slice(0,300),url:url.href,checkedAt:raw.checkedAt,source:'Trip.com',rating:Number.isFinite(rating)&&rating>=1&&rating<=5?rating:null,reviewCount:Number.isSafeInteger(count)&&count>0?count:null};}
function entries(raw){if(!Array.isArray(raw?.entries)||raw.entries.length>5000)throw Error('参考地点资料不完整');const unique=new Map();for(const item of raw.entries){const p=normalize(item);if(p&&!unique.has(p.id))unique.set(p.id,p);}return [...unique.values()];}
function nearby(rows,origin,radius,category='all'){if(!point(origin)||!Number.isFinite(radius)||radius<0||radius>10000)return [];return rows.filter(p=>point(p)&&(category==='all'||p.category===category)).map(p=>({...p,distance:distance(origin,p),reference:p,tags:{'addr:full':p.address}})).filter(p=>p.distance<=radius).sort((a,b)=>a.distance-b.distance);}
function merge(live,reference,origin,limit=200){const result=live.map(p=>({...p,distance:distance(origin,p)}));for(const ref of reference){const match=result.find(p=>p.category===ref.category&&folded(p.name)===folded(ref.name)&&distance(p,ref)<=80);if(match){match.reference=ref.reference||ref;continue;}result.push(ref);}return result.sort((a,b)=>a.distance-b.distance).slice(0,Math.max(0,Math.min(200,limit)));}
function byCity(rows,city,category='all'){return rows.filter(p=>p.city===cityName(city)&&(category==='all'||p.category===category));}
function search(rows,query,city='',limit=8){const tokens=String(query||'').trim().split(/\s+/).filter(Boolean).map(folded);if(!tokens.length)return [];return rows.filter(p=>tokens.every(token=>folded(p.city+p.name+p.address).includes(token))).sort((a,b)=>Number(b.city===cityName(city))-Number(a.city===cityName(city))).slice(0,Math.min(24,limit));}
function create({fetchImpl=(...args)=>fetch(...args),paths}={}){let rows=[],pending=null,loaded=false;return {get entries(){return rows.slice();},get loaded(){return loaded;},nearby:(origin,radius,category)=>nearby(rows,origin,radius,category),byCity:(city,category)=>byCity(rows,city,category),search:(q,city,limit)=>search(rows,q,city,limit),merge,async load(){if(loaded)return rows;if(pending)return pending;pending=(async()=>{let native=typeof location!=='undefined'&&location.protocol==='file:';try{native=native||!!parent.guanchao||!!parent.Guanchao?.native;}catch{}const addresses=paths||(native?['https://giogight.github.io/labs/nearby-catalog.json','nearby-catalog.json']:['nearby-catalog.json']);for(const url of addresses){const controller=new AbortController(),timer=setTimeout(()=>controller.abort(),5000);try{const response=await fetchImpl(url,{signal:controller.signal,cache:'no-cache'});if(!response.ok)continue;const text=await response.text();if(text.length>6000000)throw Error('参考地点资料过大');const next=entries(JSON.parse(text));if(!next.length)continue;rows=next;loaded=true;return rows;}catch{}finally{clearTimeout(timer);}}return rows;})().finally(()=>pending=null);return pending;}};}
return {normalize,entries,nearby,merge,byCity,search,create,distance};
});
