(()=>{'use strict';const A=window.GuanchaoRatingsAPI;if(!A)return;let api=null,configured=false,selected=null,selection=0,score=0,busy=false;const sessionKey='gc-rating-session-v1';const el=(tag,text,cls)=>{const node=document.createElement(tag);if(text!=null)node.textContent=text;if(cls)node.className=cls;return node;};
const dialog=el('dialog',null,'rating-auth-dialog'),head=el('div',null,'rating-dialog-head'),close=el('button','×');close.type='button';close.setAttribute('aria-label','关闭登录');close.onclick=()=>dialog.close();head.append(el('h2','登录观潮'),close);const form=el('form'),email=el('input'),password=el('input');email.type='email';email.autocomplete='email';email.required=true;email.maxLength=254;password.type='password';password.autocomplete='current-password';password.minLength=8;password.maxLength=128;password.required=true;const l1=el('label','邮箱'),l2=el('label','密码（至少8位）');l1.append(email);l2.append(password);const actions=el('div',null,'rating-auth-actions'),login=el('button','登录'),signup=el('button','注册账号');login.type='submit';signup.type='button';const authStatus=el('p',null,'rating-status');authStatus.setAttribute('role','status');actions.append(login,signup);form.append(l1,l2,actions,authStatus);dialog.append(head,form,el('p','评分公开显示平均分与人数，邮箱不会显示在地图上。','rating-hint'));document.body.append(dialog);
let finishConfig;const configReadyPromise=new Promise(resolve=>finishConfig=resolve);
window.GuanchaoCloud={get ready(){return configured;},get api(){return api;},configReadyPromise,requestLogin(){if(!configured)return false;authStatus.textContent='';if(!dialog.open)dialog.showModal();return true;}};
async function authenticate(mode){if(!api||busy)return;if(!form.reportValidity())return;busy=true;login.disabled=signup.disabled=true;authStatus.textContent='正在处理…';try{if(mode==='signup'){const result=await api.signUp(email.value,password.value);authStatus.textContent=result.confirmed?'已登录':'请检查邮箱中的确认邮件，确认后再登录。';if(!result.confirmed)return;}else await api.signIn(email.value,password.value);password.value='';dialog.close();render();await loadSelected();}catch(error){authStatus.textContent=error.message;}finally{busy=false;login.disabled=signup.disabled=false;}}
form.onsubmit=event=>{event.preventDefault();authenticate('signin');};signup.onclick=()=>authenticate('signup');
function notify(row){dispatchEvent(new CustomEvent('guanchao:place-rating-updated',{detail:row}));}
function render(){const host=document.querySelector('#nearbyPlaceDetail .place-rating');if(!host||!selected)return;host.replaceChildren();const toilet=selected.category==='toilet',title=el('h4',toilet?'干净程度':'体验评分'),publicRow=el('p','还没有公开评分','rating-public-score');publicRow.id='ratingPublicScore';host.append(title,publicRow);
if(!configured){host.append(el('p','公开评分尚未开通，接通账号服务后即可参与。','rating-hint'));return;}
const auth=el('button',api?.session?'退出账号':'登录后评分','rating-auth-link');auth.type='button';auth.onclick=async()=>{if(api.session){await api.signOut();score=0;render();}else{authStatus.textContent='';dialog.showModal();}};host.append(auth);const stars=el('div',null,'rating-stars');stars.setAttribute('role','group');stars.setAttribute('aria-label',toilet?'厕所干净程度，1至5分':'地点评分，1至5分');for(let value=1;value<=5;value++){const b=el('button','★');b.type='button';b.setAttribute('aria-label',value+' 分');b.setAttribute('aria-pressed',String(value===score));b.dataset.filled=String(value<=score);b.disabled=!api.session;b.onclick=()=>{score=value;render();loadSelected(false);};stars.append(b);}const submit=el('button','保存我的评分','rating-save');submit.type='button';submit.disabled=!api.session||!score||busy;const status=el('p',null,'rating-status');status.id='ratingStatus';status.setAttribute('role','status');submit.onclick=async()=>{if(busy||!selected)return;const p=selected,rev=selection;busy=true;submit.disabled=true;status.textContent='正在保存…';try{await api.rate(p,score);if(rev===selection){status.textContent='评分已保存，再次评分会修改你的原评分。';await loadSelected(false);}}catch(error){if(rev===selection)status.textContent=error.message;}finally{busy=false;if(rev===selection)submit.disabled=!score;}};host.append(stars,submit,status,el('p',toilet?'根据你最近使用时的情况评分，卫生状况会变化。':'根据你的实际体验评分，每个账号对同一地点计一票。','rating-hint'));}
async function loadSelected(own=true){if(!api||!selected)return;const p=selected,rev=selection;try{const rows=await api.stats([p.id]);if(rev!==selection)return;const metric=p.category==='toilet'?'cleanliness':'overall',row=rows.find(row=>row.metric===metric);if(row){const label=document.getElementById('ratingPublicScore');if(label)label.textContent=(metric==='cleanliness'?'干净程度 ':'体验 ')+row.average.toFixed(1)+' / 5 · '+row.count+' 人评分';notify(row);}if(own&&api.session){const mine=await api.own(p.id);if(rev!==selection)return;score=mine?.metric===metric?Number(mine.score):0;render();await loadSelected(false);}}catch(error){if(rev===selection){const status=document.getElementById('ratingStatus');if(status)status.textContent=error.message;}}}
addEventListener('guanchao:place-selected',event=>{try{selected=A.place(event.detail);selection++;score=0;render();loadSelected();}catch{}});
addEventListener('guanchao:places-loaded',async event=>{if(!api)return;try{const ids=(event.detail?.places||[]).slice(0,200).map(p=>A.place(p).id);for(const row of await api.stats(ids))notify(row);}catch{}});
addEventListener('message',event=>{if(event.source!==parent||(event.origin!==location.origin&&!(location.protocol==='file:'&&event.origin==='null')))return;if(event.data?.type==='guanchao:pause'&&dialog.open)dialog.close();});
async function init(){let native=location.protocol==='file:';try{native=native||!!parent.guanchao||!!parent.Guanchao?.native;}catch{}const paths=native?['https://giogight.github.io/ratings-config.json',new URL('../ratings-config.json',location.href).href]:[new URL('../ratings-config.json',location.href).href];for(const path of paths){const c=new AbortController(),timer=setTimeout(()=>c.abort(),5000);try{const r=await fetch(path,{signal:c.signal,cache:'no-cache'});if(!r.ok)continue;const cfg=await r.json();if(!A.config(cfg)){configured=false;break;}api=A.create(cfg,{onSession:value=>{dispatchEvent(new CustomEvent('guanchao:cloud-auth',{detail:{signedIn:!!value}}));try{value?sessionStorage.setItem(sessionKey,JSON.stringify(value)):sessionStorage.removeItem(sessionKey);}catch{}}});configured=true;let saved=null;try{const raw=sessionStorage.getItem(sessionKey);if(raw?.length<20000)saved=JSON.parse(raw);}catch{}if(saved)await api.restore(saved);break;}catch{}finally{clearTimeout(timer);}}finishConfig(configured);dispatchEvent(new CustomEvent('guanchao:cloud-auth',{detail:{signedIn:!!api?.session}}));render();loadSelected();}
init();
})();

