(function(root){'use strict';
const maxOptions=200;
function parseOptions(text){if(typeof text!=='string'||text.length>25000)throw Error('选项文字太多，请分成几次选择。');const options=text.split(/\r?\n/).map(s=>s.trim()).filter(Boolean);if(options.length>maxOptions)throw Error('一次最多200个选项。');if(options.some(s=>s.length>120||/[\u0000-\u001f\u007f]/.test(s)))throw Error('每个选项最多120字，请移除控制字符。');return options;}
function randomIndex(count,source=root.crypto){if(!Number.isInteger(count)||count<1||count>maxOptions)throw Error('选项数量不正确。');if(!source?.getRandomValues)throw Error('当前设备无法生成随机结果。');const limit=Math.floor(4294967296/count)*count,v=new Uint32Array(1);do{source.getRandomValues(v);}while(v[0]>=limit);return v[0]%count;}
const api={parseOptions,randomIndex,maxOptions};if(typeof module==='object'&&module.exports)module.exports=api;if(!root.document)return;
const $=id=>document.getElementById(id),key='gc-decision-options-v1',colors=['#d9c4ef','#b5cde3','#c5dcda','#baa6d9','#d4b8d6','#b1badc'];let options=[],busy=false,angle=0,timer=null,pending=null,saveTimer;
const reduced=()=>matchMedia('(prefers-reduced-motion: reduce)').matches;
function render(){const canvas=$('wheelCanvas'),ctx=canvas.getContext('2d');ctx.clearRect(0,0,640,640);const count=options.length||1,step=Math.PI*2/count;for(let i=0;i<count;i++){const start=-Math.PI/2+i*step;ctx.beginPath();ctx.moveTo(320,320);ctx.arc(320,320,313,start,start+step);ctx.closePath();ctx.fillStyle=colors[i%colors.length];ctx.fill();ctx.strokeStyle='#ffffff80';ctx.lineWidth=count>50?1:2;ctx.stroke();if(options.length&&count<=24){ctx.save();ctx.translate(320,320);ctx.rotate(start+step/2);ctx.textAlign='right';ctx.fillStyle='#4a385f';ctx.font=(count>12?'20':'25')+'px "Microsoft YaHei",sans-serif';const label=options[i].length>9?options[i].slice(0,8)+'…':options[i];ctx.fillText(label,278,8);ctx.restore();}}$('optionCount').textContent=options.length?options.length+' 个选项'+(options.length>24?' · 选项较多，转盘不显示文字，结果会完整展示。':''): '支持任意日常选项，每行一个。';$('spinButton').disabled=$('wheelCenter').disabled=busy||options.length<2;}
function finish(){clearTimeout(timer);timer=null;if(!pending)return;const p=pending;pending=null;busy=false;if(p.kind==='wheel'){$('wheelCanvas').style.transition='none';$('wheelCanvas').style.transform='rotate('+angle+'deg)';$('wheelResult').replaceChildren(document.createTextNode(options[p.index]),Object.assign(document.createElement('small'),{textContent:'选中了第 '+(p.index+1)+' 个选项。'}));}else{$('coin').classList.remove('flipping');$('coin').dataset.result=p.index?'tails':'heads';$('coinResult').textContent=p.index?'月亮 · 反面':'太阳 · 正面';}$('options').disabled=false;$('coinButton').disabled=false;render();}
function refresh(){try{options=parseOptions($('options').value);$('wheelResult').textContent=options.length>=2?'准备好了，转一下。':'先写下至少两个选项。';$('saveStatus').textContent='';render();clearTimeout(saveTimer);saveTimer=setTimeout(()=>{try{localStorage.setItem(key,$('options').value);}catch{$('saveStatus').textContent='本机保存失败，当前选项仍可使用。';}},300);}catch(e){$('saveStatus').textContent=e.message;$('spinButton').disabled=$('wheelCenter').disabled=true;}}
try{const saved=localStorage.getItem(key);if(saved){options=parseOptions(saved);$('options').value=saved;}}catch{$('saveStatus').textContent='本机选项暂时无法读取，原记录未改动。';}render();if(options.length>=2)$('wheelResult').textContent='选项已准备好，转一下。';$('options').oninput=refresh;
$('spinButton').onclick=()=>{if(busy)return;try{const index=randomIndex(options.length);busy=true;pending={kind:'wheel',index};$('options').disabled=true;$('spinButton').disabled=$('wheelCenter').disabled=true;$('wheelResult').textContent='正在转动…';const step=360/options.length,target=(360-(index+.5)*step)%360,current=((angle%360)+360)%360;angle+=1800+(target-current+360)%360;const canvas=$('wheelCanvas');canvas.style.transition=reduced()?'none':'transform 3.6s cubic-bezier(.16,.68,.12,1)';canvas.style.transform='rotate('+angle+'deg)';timer=setTimeout(finish,reduced()?0:3650);}catch(e){$('wheelResult').textContent=e.message;}};
$('coinButton').onclick=()=>{if(busy)return;try{const index=randomIndex(2);busy=true;pending={kind:'coin',index};$('coinButton').disabled=true;$('coinResult').textContent='硬币在空中…';const coin=$('coin');coin.style.setProperty('--coin-angle',index?'2340deg':'2160deg');coin.classList.add('flipping');timer=setTimeout(finish,reduced()?0:1450);}catch(e){$('coinResult').textContent=e.message;}};
$('wheelCenter').onclick=()=>$('spinButton').click();
document.querySelectorAll('[data-mode]').forEach(b=>b.onclick=()=>{finish();const wheel=b.dataset.mode==='wheel';$('wheelPanel').hidden=!wheel;$('coinPanel').hidden=wheel;document.querySelectorAll('[data-mode]').forEach(t=>t.setAttribute('aria-pressed',String(t===b)));});
addEventListener('message',e=>{if(e.source!==parent||(e.origin!==location.origin&&!(location.protocol==='file:'&&e.origin==='null')))return;if(e.data?.type==='guanchao:theme'&&['day','night'].includes(e.data.theme))document.documentElement.dataset.theme=e.data.theme;if(e.data?.type==='guanchao:pause')finish();});document.addEventListener('visibilitychange',()=>{if(document.hidden)finish();});
})(typeof window!=='undefined'?window:globalThis);


